# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='users',
            new_name='user',
        ),
    ]
